#!/usr/bin/env bash

path_file=$1
ip_address=$2
username=$3
path_ssh=$4

if [[ $# < 4 ]];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i $path_ssh $path_file $username@$ip_address:~/
fi
