#!/usr/bin/env bash
#This script installs and configures nginx in the server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
