#!/usr/bin/env bash
#This script installs and configures nginx in the server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default

service nginx restart
