#!/usr/bin/env bash
#This script configures a load balancer
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i '$ a frontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes' /etc/haproxy/haproxy.cfg
sudo sed -i '$ a backend backendnodes\n\tbalance roundrobin\n\toption forwardfor\n\thttp-request set-header X-Forwarded-Port %[dst_port]\n\thttp-request add-header X-Forwarded-Proto https if { ssl_fc }\n\toption httpchk HEAD / HTTP/1.1\\r\\nHost:localhost\n\tserver node1 54.167.96.160:80 check\n\tserver node2 100.25.134.74:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
